
<html ng-app>
    <head>
        <title> ZF2 + Angular </title>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
        <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    </head>
    <body>


    <!-- Wrap all page content here -->
    <div id="wrap">

        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">School of Net</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#/categorias">Categorias</a></li>
                        <li><a href="#/produtos">Produtos</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <?=$this->content;?>

        <div id="footer">
            <div class="container">
                <p class="text-muted credit">School of Net.</p>
            </div>
        </div>
    </div>


    <!-- div ng-controller="CtrlApp">

            <input type="text" ng-model="nome">
            <h1>{{nome}}</h1>
        </div>

    <script>
        var CtrlApp = function($scope){
            $scope.nome = "Nelson";
        }
    </script -->

    </body>
</html>
